<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\admin\controller;


use app\admin\model\ConfigGroup;
use app\admin\service\ConfigService;
use app\common\controller\Backend;
use think\facade\Db;
use think\facade\View;

/**
 * 配置管理-控制器
 * @author 牧羊人
 * @since 2020/7/1
 * Class Config
 * @package app\admin\controller
 */
class Config extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/1
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Config();
        $this->service = new ConfigService();
    }

    public function test(){
//        $a = '{"msg":"操作成功","code":0,"data":[{"id":22,"name":"templateParam","title":"模板参数","value":"{\"code\":\"12346\"}","options":"","group_id":4,"sub_group":0,"type":"text","status":1,"sort":20,"remark":"","create_user":1,"create_time":"2021-01-24 15:23:03","update_user":1,"update_time":"2021-06-04 14:21:27","mark":1,"create_user_name":"管理员","update_user_name":"管理员","type_name":"单行文本","group_name":"短信设置"},{"id":21,"name":"templateCode","title":"模板CODE","value":"SMS_1812234235","options":"","group_id":4,"sub_group":0,"type":"text","status":1,"sort":15,"remark":"","create_user":1,"create_time":"2021-01-24 15:23:03","update_user":1,"update_time":"2021-06-04 14:21:27","mark":1,"create_user_name":"管理员","update_user_name":"管理员","type_name":"单行文本","group_name":"短信设置"},{"id":20,"name":"signName","title":"短信签名","value":"研发中心","options":"","group_id":4,"sub_group":0,"type":"text","status":1,"sort":10,"remark":"","create_user":1,"create_time":"2021-01-24 15:23:03","update_user":1,"update_time":"2021-06-04 14:21:27","mark":1,"create_user_name":"管理员","update_user_name":"管理员","type_name":"单行文本","group_name":"短信设置"},{"id":19,"name":"accessKeySecret","title":"短信Secret","value":"xkki8v10wV3Ux637mk4eNNykTaMzNFGH","options":"","group_id":4,"sub_group":0,"type":"text","status":1,"sort":5,"remark":"","create_user":1,"create_time":"2021-01-24 15:23:03","update_user":1,"update_time":"2021-06-04 14:21:27","mark":1,"create_user_name":"管理员","update_user_name":"管理员","type_name":"单行文本","group_name":"短信设置"},{"id":18,"name":"accessKeyId","title":"短信KeyId","value":"LTAIiiZGTbjvFJKHMAE","options":"","group_id":4,"sub_group":0,"type":"text","status":1,"sort":1,"remark":"","create_user":1,"create_time":"2021-01-24 15:23:03","update_user":1,"update_time":"2021-06-04 14:21:27","mark":1,"create_user_name":"管理员","update_user_name":"管理员","type_name":"单行文本","group_name":"短信设置"}],"count":5}';
//        $data = json_decode($a,1);
//        foreach($data['data'] as $data){
//            unset($data['type_name']);
//            unset($data['image_url']);
//            Db::table('think_config')->insert($data);
//
//        }
    }

    /**
     * 数据列表页
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 牧羊人
     * @since 2020/7/1
     */
    public function index()
    {
        // 配置分组ID
        $group_id = request()->param('group_id', 1);

        // 获取配置分组
        $configGroupModel = new ConfigGroup();
        $configGroupList = $configGroupModel->where(['mark' => 1])->select();
        return parent::index([
            'group_id' => $group_id,
            'configGroupList' => $configGroupList->toArray(),
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * 添加或编辑
     * @return mixed
     * @since 2020/7/1
     * @author 牧羊人
     */
    public function edit()
    {
        // 配置类型
        View::assign("typeList", config("admin.config_type"));
        // 配置分组
        View::assign("groupList", Db::name('configGroup')->where(['mark' => 1])->select()->toArray());
        // 分组ID
        $groupId = request()->param('group_id', 0);
        // 初始化默认值
        return parent::edit([
            'group_id' => $groupId,
        ]); // TODO: Change the autogenerated stub
    }

}