<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\admin\controller;


use app\common\controller\Backend;
use think\facade\Db;

/**
 * 数据库管理-控制器
 * @author 牧羊人
 * @since 2020/7/4
 * Class Database
 * @package app\admin\controller
 */
class Database extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/4
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 数据列表页
     * @return array|mixed
     * @since 2020/7/4
     * @author 牧羊人
     */
    public function index()
    {
        if (IS_POST) {
            $list = Db::query('SHOW TABLE STATUS');
            $list = array_map('array_change_key_case', $list);
            $title = '数据备份';

            return $message = array(
                "msg" => '操作成功',
                "code" => 0,
                "data" => $list,
                "count" => 10,
            );
        }
        return $this->render();
    }
}