<?php 
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\admin\controller;


use app\admin\service\Demo3Service;
use app\common\controller\Backend;

/**
 * 演示管理-控制器
 * @author 牧羊人
 * @since: 2021/02/06
 * Class Demo3
 * @package app\admin\controller
 */
class Demo3 extends Backend
{
    /**
     * 初始化方法
     * @author 牧羊人
     * @since: 2021/02/06
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Demo3();
        $this->service = new Demo3Service();
    }
	
	                	
	/**
	 * 设置状态	 
	 * @return mixed
	 * @since 2021/02/06	 
	 * @author 牧羊人	 
	 */
	public function setStatus()
	{
		if (IS_POST) {
			$result = $this->service->setStatus();
			return $result;
		}
	}
	        	
	/**
	 * 设置是否VIP	 
	 * @return mixed
	 * @since 2021/02/06	 
	 * @author 牧羊人	 
	 */
	public function setIsVip()
	{
		if (IS_POST) {
			$result = $this->service->setIsVip();
			return $result;
		}
	}
	                        }