<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\admin\controller;


use app\admin\service\ItemService;
use app\common\controller\Backend;
use think\facade\View;

/**
 * 站点-控制器
 * @author 牧羊人
 * @since 2020/7/2
 * Class Item
 * @package app\admin\controller
 */
class Item extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/2
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Item();
        $this->service = new ItemService();
    }

    /**
     * 添加或编辑
     * @return mixed
     * @since 2020/7/2
     * @author 牧羊人
     */
    public function edit()
    {
        // 站点类型
        View::assign("typeList", config("admin.item_type"));
        return parent::edit(); // TODO: Change the autogenerated stub
    }
}