<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\admin\controller;


use app\admin\service\NoticeService;
use app\common\controller\Backend;
use think\facade\View;

/**
 * 通知公告-控制器
 * @author 牧羊人
 * @since 2020/7/5
 * Class Notice
 * @package app\admin\controller
 */
class Notice extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/7/5
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Notice();
        $this->service = new NoticeService();
    }

    /**
     * 数据列表页
     * @return mixed
     * @since 2020/7/5
     * @author 牧羊人
     */
    public function index()
    {
        // 通知来源
        View::assign("sourceList", config("admin.notice_source"));
        return parent::index(); // TODO: Change the autogenerated stub
    }

    /**
     * 添加或编辑
     * @return mixed
     * @since 2020/7/5
     * @author 牧羊人
     */
    public function edit()
    {
        // 通知来源
        View::assign("sourceList", config("admin.notice_source"));
        // 通知状态
        View::assign("statusList", config('admin.notice_status'));
        return parent::edit(); // TODO: Change the autogenerated stub
    }
}