<?php


namespace app\admin\controller;


use app\common\controller\Backend;

/**
 * 统计报表
 * @author 牧羊人
 * @since 2020/8/16
 * Class Statistics
 * @package app\admin\controller
 */
class Statistics extends Backend
{
    /**
     * 初始化
     * @author 牧羊人
     * @since 2020/8/16
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 统计首页
     * @return mixed
     * @since 2020/8/16
     * @author 牧羊人
     */
    public function index()
    {
        // 取消模板布局
        $this->app->view->layout(false);
        return $this->render();
    }
}