<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace app\admin\service;


use app\admin\model\AdSort;
use app\common\service\BaseService;

/**
 * 广告位管理-服务类
 * @author 牧羊人
 * @since 2020/7/2
 * Class AdSortService
 * @package app\admin\service
 */
class AdSortService extends BaseService
{
    /**
     * 构造函数
     * @author 牧羊人
     * @since 2020/7/2
     * AdSortService constructor.
     */
    public function __construct()
    {
        $this->model = new AdSort();
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2021/1/24
     * @author 牧羊人
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
        // 站点栏目
        $itemArr = explode(",", $data['cate_id']);
        if (!empty($itemArr)) {
            $data['item_id'] = $itemArr[0];
            $data['cate_id'] = $itemArr[1];
        }
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

}